// Data for RealLife English
const LEVELS = [
  { id:'A1', label:'Beginner', name:'Beginner (A1)', desc:'Simple words, short sentences' },
  { id:'A2', label:'Elementary', name:'Elementary (A2)', desc:'Everyday phrases' },
  { id:'B1', label:'Intermediate', name:'Intermediate (B1)', desc:'Natural conversations' },
  { id:'B2', label:'Upper-Int.', name:'Upper-Intermediate (B2)', desc:'Fluent & detailed' },
  { id:'C1', label:'Advanced', name:'Advanced (C1)', desc:'Native-like nuance' },
];

const SITUATIONS = [
  { id:'airport', icon:'✈️', title:'Airport', sub:'Check-in', coming:false },
  { id:'hotel', icon:'🏨', title:'Hotel', sub:'Check-in & breakfast', coming:false },
  { id:'restaurant', icon:'🍽️', title:'Restaurant', sub:'Order & pay', coming:false },
  { id:'taxi', icon:'🚕', title:'Taxi', sub:'Address & price', coming:false },
  { id:'shopping', icon:'🛍️', title:'Shopping', sub:'Size & price', coming:true },
  { id:'hospital', icon:'🏥', title:'Hospital', sub:'Pharmacy', coming:true },
  { id:'interview', icon:'💼', title:'Job Interview', sub:'Short interview', coming:true },
  { id:'meeting', icon:'🤝', title:'Business', sub:'Meeting', coming:true },
  { id:'directions', icon:'🗺️', title:'Directions', sub:'Ask the way', coming:true },
  { id:'phone', icon:'📞', title:'Phone Call', sub:'Make a call', coming:true },
  { id:'passport', icon:'🛂', title:'Passport Control', sub:'Questions', coming:true },
  { id:'plane', icon:'🛫', title:'Plane', sub:'On board', coming:true },
  { id:'hotel2', icon:'🛎️', title:'Hotel Problem', sub:'Fix an issue', coming:true },
  { id:'cafe', icon:'☕', title:'Café', sub:'Order coffee', coming:true },
  { id:'train', icon:'🚆', title:'Train Station', sub:'Tickets', coming:true },
  { id:'luggage', icon:'🧳', title:'Luggage', sub:'Lost baggage', coming:true },
];

const SCENARIOS = {
airport: {
  id:'airport', icon:'✈️', title:'Airport — Check-in', goal:'Get your boarding pass',
  desc:'You are at the airport. You need to check in for your flight to London.',
  character:{ name:'Agent', role:'Check-in Agent', avatar:'👩‍💼' },
  turns:[
    { agent:"Good morning. May I see your passport, please?",
      hint:"Give your passport and greet back politely.",
      useful:["passport","here you are","sure"],
      example:"Sure, here you are.",
      correct:"Sure, here you are.",
      natural:"Sure, here you are.",
      keywords:["here","sure","passport","please","you are"],
      phrases:["Here you are","May I see...?"] },
    { agent:"Thank you. Do you have any bags to check in?",
      hint:"Say if you have a bag and how many.",
      useful:["bag","check in","one bag","no"],
      example:"Yes, one bag to check in, please.",
      correct:"Yes, I have one bag to check in.",
      natural:"Yes, one bag to check in, please.",
      keywords:["bag","check","one","yes"],
      phrases:["to check in"] },
    { agent:"Would you like a window or an aisle seat?",
      hint:"Choose a seat and be polite.",
      useful:["window","aisle","prefer","please"],
      example:"A window seat, please.",
      correct:"A window seat, please.",
      natural:"Could I have a window seat, please?",
      keywords:["window","aisle","seat"],
      phrases:["Could I have...?"] },
    { agent:"Here is your boarding pass. Boarding is at gate 12 at 9:40. Enjoy your flight!",
      hint:"Thank the agent politely.",
      useful:["thank you","thanks","gate"],
      example:"Thank you very much!",
      correct:"Thank you very much!",
      natural:"Thank you so much!",
      keywords:["thank"],
      phrases:["Thank you very much"] },
  ]
},
hotel: {
  id:'hotel', icon:'🏨', title:'Hotel — Check-in', goal:'Check in and ask about breakfast',
  desc:'You arrive at the Grand Hotel. You have a reservation for 3 nights.',
  character:{ name:'Receptionist', role:'Hotel Receptionist', avatar:'👨‍💼' },
  turns:[
    { agent:"Good evening. Welcome to the Grand Hotel. Do you have a reservation?",
      hint:"Say you booked a room.",
      useful:["reservation","booked","yes"],
      example:"Yes, I booked a room for three nights.",
      correct:"Yes, I have a reservation.",
      natural:"Yes, I have a reservation under the name Alex.",
      keywords:["reservation","booked","yes"],
      phrases:["I have a reservation"] },
    { agent:"Could I have your name, please?",
      hint:"Give your name clearly.",
      useful:["my name is","I am"],
      example:"My name is Alex Johnson.",
      correct:"My name is Alex Johnson.",
      natural:"It's Alex Johnson.",
      keywords:["alex","johnson","name"],
      phrases:["My name is..."] },
    { agent:"Thank you. I found your reservation. You're staying for three nights. Is that correct?",
      hint:"Confirm the information.",
      useful:["yes","correct","that's right"],
      example:"Yes, that's correct.",
      correct:"Yes, that's correct.",
      natural:"Yes, that's right.",
      keywords:["yes","correct","right"],
      phrases:["That's correct"] },
    { agent:"Perfect. Here's your key. Your room is on the fourth floor. Is there anything else?",
      hint:"Ask about breakfast.",
      useful:["breakfast","included","time"],
      example:"Is breakfast included?",
      correct:"Is breakfast included?",
      natural:"Is breakfast included in the price?",
      keywords:["breakfast","included"],
      phrases:["Is ... included?"] },
    { agent:"Yes, breakfast is from 7 to 10 a.m. in the restaurant on the ground floor.",
      hint:"Thank and finish politely.",
      useful:["thank you","great","thanks"],
      example:"Great, thank you!",
      correct:"Great, thank you!",
      natural:"Wonderful, thank you!",
      keywords:["thank","great"],
      phrases:["Thank you!"] },
  ]
},
restaurant: {
  id:'restaurant', icon:'🍽️', title:'Restaurant', goal:'Order, change a dish and pay',
  desc:'You are at an Italian restaurant. You want to order dinner.',
  character:{ name:'Waiter', role:'Waiter', avatar:'🤵' },
  turns:[
    { agent:"Good evening! Are you ready to order?",
      hint:"Say you need a moment or that you're ready.",
      useful:["ready","menu","order"],
      example:"Yes, I'd like to order, please.",
      correct:"Yes, I'd like to order.",
      natural:"Yes, I'd like to order, please.",
      keywords:["order","ready","like"],
      phrases:["I'd like to..."] },
    { agent:"Of course. What would you like to have?",
      hint:"Order a dish. Use 'I'd like' or 'Could I have'.",
      useful:["I'd like","pasta","pizza","salad"],
      example:"I'd like the pasta, please.",
      correct:"I'd like the pasta, please.",
      natural:"Could I have the pasta, please?",
      keywords:["like","pasta","pizza","salad","have"],
      phrases:["Could I have...?"] },
    { agent:"Would you like anything to drink?",
      hint:"Order a drink or say no.",
      useful:["water","wine","juice","no thanks"],
      example:"Just water, please.",
      correct:"Just water, please.",
      natural:"Just water, please.",
      keywords:["water","wine","juice","drink"],
      phrases:["Just water, please"] },
    { agent:"Great choice. I'll be right back with your order.",
      hint:"Say thank you.",
      useful:["thank you","thanks","great"],
      example:"Thank you!",
      correct:"Thank you!",
      natural:"Thank you!",
      keywords:["thank"],
      phrases:["Thank you"] },
    { agent:"How was everything? Would you like the bill?",
      hint:"Ask for the bill and how to pay.",
      useful:["bill","check","pay","card"],
      example:"Yes, the bill, please. Can I pay by card?",
      correct:"Yes, the bill, please. Can I pay by card?",
      natural:"Could I have the bill, please?",
      keywords:["bill","pay","card","check"],
      phrases:["Could I have the bill?"] },
  ]
},
taxi: {
  id:'taxi', icon:'🚕', title:'Taxi', goal:'Tell the address and agree on price',
  desc:'You need to get to the Central Hotel. Ask about the price.',
  character:{ name:'Driver', role:'Taxi Driver', avatar:'👨‍✈️' },
  turns:[
    { agent:"Hello! Where would you like to go?",
      hint:"Say your destination clearly.",
      useful:["Central Hotel","to","go to"],
      example:"To the Central Hotel, please.",
      correct:"To the Central Hotel, please.",
      natural:"Could you take me to the Central Hotel, please?",
      keywords:["central","hotel"],
      phrases:["Could you take me to...?"] },
    { agent:"Central Hotel — got it. Do you know the address?",
      hint:"You don't know the exact address — say it's in the center.",
      useful:["center","downtown","not sure"],
      example:"It's in the city center, near the station.",
      correct:"It's in the city center.",
      natural:"It's downtown, near the station.",
      keywords:["center","downtown","station"],
      phrases:["It's in the city center"] },
    { agent:"No problem, I know where it is. It will be about 15 euros. Is that okay?",
      hint:"Agree and confirm.",
      useful:["okay","fine","yes","that's fine"],
      example:"Yes, that's fine. Let's go.",
      correct:"Yes, that's fine.",
      natural:"Yes, that's fine with me.",
      keywords:["yes","fine","okay"],
      phrases:["That's fine"] },
    { agent:"Great, please get in. We'll be there in about 10 minutes.",
      hint:"Thank the driver.",
      useful:["thank you","thanks","great"],
      example:"Thank you!",
      correct:"Thank you!",
      natural:"Thanks!",
      keywords:["thank"],
      phrases:["Thank you"] },
  ]
}
};

const FREE_TOPICS = [
  { id:'travel', icon:'✈️', title:'Travel' },
  { id:'work', icon:'💼', title:'Work' },
  { id:'family', icon:'👨‍👩‍👧', title:'Family' },
  { id:'food', icon:'🍽️', title:'Food' },
  { id:'movies', icon:'🎬', title:'Movies' },
  { id:'hobbies', icon:'🎨', title:'Hobbies' },
  { id:'tech', icon:'💻', title:'Technology' },
  { id:'life', icon:'🏠', title:'Everyday life' },
];

const FREE_STARTERS = {
  travel:"You're visiting London for the first time. What are you planning to do there?",
  work:"What do you do for work? Do you enjoy it?",
  family:"Do you live with your family? Tell me a bit about them.",
  food:"What's your favorite food? Can you cook it?",
  movies:"What kind of movies do you like? Any recent favorite?",
  hobbies:"What do you like to do in your free time?",
  tech:"How has technology changed your daily life?",
  life:"How was your day today? Anything interesting happened?"
};

const ACHIEVEMENTS_LIST = [
  { id:'first', icon:'🏆', title:'First Conversation', desc:'Complete your first scenario', check:(s)=>s.completed.length>=1 },
  { id:'airport', icon:'✈️', title:'Airport Expert', desc:'Complete 5 airport scenarios', check:(s)=>s.completed.filter(c=>c.id==='airport' || c.id.startsWith('gen-') && c.category==='Travel').length>=5 },
  { id:'streak7', icon:'🔥', title:'7 Day Streak', desc:'Practice 7 days in a row', check:(s)=>s.streak>=7 },
  { id:'perfect', icon:'✨', title:'No Mistakes', desc:'Complete a scenario with 100%', check:(s)=>s.completed.some(c=>c.score===100) },
  { id:'ten', icon:'💯', title:'10 Scenarios', desc:'Complete 10 scenarios', check:(s)=>s.completed.length>=10 },
  { id:'infinite', icon:'∞', title:'Infinite Explorer', desc:'Complete 5 AI-generated scenarios', check:(s)=>s.completed.filter(c=>c.id.startsWith('gen-')).length>=5 },
  { id:'journey', icon:'🌎', title:'Endless Journey', desc:'Complete an Endless Journey', check:(s)=>s.completed.some(c=>c.id==='journey-done') },
];

const PURPOSES = [
  {id:'travel', icon:'✈️', title:"I'm travelling", desc:"Airport → Hotel → Restaurant → Taxi", cats:['Travel','Hotels','Food','Transport']},
  {id:'work', icon:'💼', title:"I work internationally", desc:"Meeting → Presentation → Interview", cats:['Work','Social']},
  {id:'move', icon:'🏠', title:"I'm moving abroad", desc:"Housing → Bank → Doctor → Shopping", cats:['Everyday','Shopping','Hotels']},
  {id:'study', icon:'📚', title:"I'm studying", desc:"Everyday → Social → Work", cats:['Everyday','Social','Work']},
  {id:'general', icon:'🌟', title:"Just improve my English", desc:"Mixed real-life situations", cats:null},
];
